/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import model.Calculadora;
import util.arquivo;

/**
 *
 * @author Gabriel
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFNumero1 = new javax.swing.JTextField();
        jTFNumero2 = new javax.swing.JTextField();
        jButtonDividir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAHistorico = new javax.swing.JTextArea();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonSomar = new javax.swing.JButton();
        jButtonSubtrair = new javax.swing.JButton();
        jLabelNum2 = new javax.swing.JLabel();
        jLabelNum1 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jButtonHistorico = new javax.swing.JButton();
        jButtonLimparHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTFNumero1.setBackground(new java.awt.Color(255, 255, 255));
        jTFNumero1.setForeground(new java.awt.Color(0, 0, 0));
        jTFNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumero1ActionPerformed(evt);
            }
        });

        jTFNumero2.setBackground(new java.awt.Color(255, 255, 255));
        jTFNumero2.setForeground(new java.awt.Color(0, 0, 0));

        jButtonDividir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonDividir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDividir.setText("Dividir");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTAHistorico.setBackground(new java.awt.Color(255, 255, 255));
        jTAHistorico.setColumns(20);
        jTAHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jTAHistorico.setRows(5);
        jScrollPane1.setViewportView(jTAHistorico);

        jButtonMultiplicar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMultiplicar.setText("Multiplicar");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButtonSomar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonSomar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSomar.setText("Somar");
        jButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomarActionPerformed(evt);
            }
        });

        jButtonSubtrair.setBackground(new java.awt.Color(204, 255, 255));
        jButtonSubtrair.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSubtrair.setText("Subtrair");
        jButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtrairActionPerformed(evt);
            }
        });

        jLabelNum2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNum2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNum2.setText("Digite o segundo número:");
        jLabelNum2.setOpaque(true);

        jLabelNum1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNum1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNum1.setText("Digite o primeiro número:");
        jLabelNum1.setOpaque(true);

        jLabelResultado.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelResultado.setOpaque(true);

        jButtonHistorico.setBackground(new java.awt.Color(204, 255, 255));
        jButtonHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHistorico.setText("Historico");
        jButtonHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoActionPerformed(evt);
            }
        });

        jButtonLimparHistorico.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimparHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimparHistorico.setText("Limpar Historico");
        jButtonLimparHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(jLabelNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonLimparHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSomar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSubtrair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSomar)
                        .addComponent(jButtonSubtrair)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDividir)
                        .addComponent(jButtonMultiplicar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelNum2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFNumero2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimparHistorico)))
                    .addComponent(jButtonHistorico))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumero1ActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        // TODO add your handling code here:
        if (jTFNumero1.getText().trim().isEmpty() || jTFNumero2.getText().trim().isEmpty()){
            jLabelResultado.setText("Preencha todos os campos!");           
            jTFNumero1.requestFocus();
            return;
        }

        try {

            double num1 = Double.parseDouble(jTFNumero1.getText());
            double num2 = Double.parseDouble(jTFNumero2.getText());

            Calculadora calc = new Calculadora();
            double resultado = calc.dividir(num1, num2);

            jLabelResultado.setText("Resultado: " + resultado);

            jTAHistorico.append(num1 + " / " + num2 + " = " + resultado + "\n" );
            String linha = num1 + "/" + num2 + " = " + resultado; //guardar histórico das operações//
            arquivo.salvarLinha(linha);
               
            jLabelResultado.setForeground(Color.RED);
        } catch (NumberFormatException ex) {
            jLabelResultado.setText("Digite apenas valores numéricos!");
        } catch (ArithmeticException ex) { 
            jLabelResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTFNumero1.setText("");
        jTFNumero2.setText("");
        jLabelResultado.setText("");
        jTFNumero1.requestFocus();//cursor vai pro campo do número 1//
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        // TODO add your handling code here:
        
        if (jTFNumero1.getText().trim().isEmpty() || jTFNumero2.getText().trim().isEmpty()){
            jLabelResultado.setText("Preencha todos os campos! \n");
            jTFNumero1.requestFocus();
            return;
        }
    
        try{
            double num1 = Double.parseDouble(jTFNumero1.getText());
            double num2 = Double.parseDouble(jTFNumero2.getText());

            Calculadora calc = new Calculadora();
            double resultado = calc.multiplicar(num1, num2);

            jLabelResultado.setText("Resultado: " + resultado);
            jTAHistorico.append(num1 + " * " + num2 + " = " + resultado + "\n");
            String linha = num1 + " * " + num2 + " = " + resultado;
            arquivo.salvarLinha(linha);
            jLabelResultado.setForeground(Color.RED);
        } catch (NumberFormatException ex) {
            jLabelResultado.setText("Digite apenas valores numéricos!");
        } catch (ArithmeticException ex) { 
            jLabelResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomarActionPerformed
        // TODO add your handling code here:
        
        if (jTFNumero1.getText().trim().isEmpty() || jTFNumero2.getText().trim().isEmpty()){
            jLabelResultado.setText("Preencha todos os campos! \n");
            jTFNumero1.requestFocus();
            return;
        }
        try{
            
            double num1 = Double.parseDouble(jTFNumero1.getText());
            double num2 = Double.parseDouble(jTFNumero2.getText());

            Calculadora calc = new Calculadora();
            double resultado = calc.somar(num1, num2);

            jLabelResultado.setText("Resultado: " + resultado);
            jTAHistorico.append(num1 + " + " + num2 + " = " + resultado + "\n");
            String linha = num1 + " + " + num2 + " = " + resultado;
            arquivo.salvarLinha(linha);
            jLabelResultado.setForeground(Color.RED);
        } catch (NumberFormatException ex) {
            jLabelResultado.setText("Digite apenas valores numéricos!");
        } catch (ArithmeticException ex) { 
            jLabelResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSomarActionPerformed

    private void jButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtrairActionPerformed
        // TODO add your handling code here:
        
        if (jTFNumero1.getText().trim().isEmpty() || jTFNumero2.getText().trim().isEmpty()){
            jLabelResultado.setText("Preencha todos os campos! \n");
            jTFNumero1.requestFocus();
            return;
        }

        try {

            double num1 = Double.parseDouble(jTFNumero1.getText());
            double num2 = Double.parseDouble(jTFNumero2.getText());

            Calculadora calc = new Calculadora();
            double resultado = calc.subtrair(num1, num2);

            jLabelResultado.setText("Resultado: " + resultado);
            jTAHistorico.append(num1 + " - " + num2 + " = " + resultado + "\n" );
            String linha = num1 + " - " + num2 + " = " + resultado;
            arquivo.salvarLinha(linha);
            jLabelResultado.setForeground(Color.RED);
        } catch (NumberFormatException ex) {
            jLabelResultado.setText("Digite apenas valores numéricos! \n");
        } catch (ArithmeticException ex) { 
            jLabelResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSubtrairActionPerformed

    private void jButtonHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoActionPerformed
        // TODO add your handling code here:
        new TelaSecundaria().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHistoricoActionPerformed

    private void jButtonLimparHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparHistoricoActionPerformed
        // TODO add your handling code here:
        jTAHistorico.setText("");
        jTFNumero1.requestFocus();
        
    }//GEN-LAST:event_jButtonLimparHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimparHistorico;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSubtrair;
    private javax.swing.JLabel jLabelNum1;
    private javax.swing.JLabel jLabelNum2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAHistorico;
    private javax.swing.JTextField jTFNumero1;
    private javax.swing.JTextField jTFNumero2;
    // End of variables declaration//GEN-END:variables
}
